"""empty message

Revision ID: 0bc09c144748
Revises: ab61467dee5b
Create Date: 2024-03-19 10:44:40.374638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bc09c144748'
down_revision = 'ab61467dee5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('state')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('state')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=250), nullable=False))

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=250), nullable=False))

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=250), nullable=False))

    # ### end Alembic commands ###
