"""empty message

Revision ID: 0d94b271a5c0
Revises: 46b593cd8261
Create Date: 2024-03-18 12:04:46.185294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d94b271a5c0'
down_revision = '46b593cd8261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('experience')
        batch_op.drop_column('role')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
