"""empty message

Revision ID: 0f8109b7acdc
Revises: 
Create Date: 2024-03-22 17:01:00.670501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8109b7acdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_handle', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_handle')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('available', sa.String(length=250), nullable=False),
    sa.Column('city', sa.String(length=250), nullable=False),
    sa.Column('country', sa.String(length=250), nullable=False),
    sa.Column('profession', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=250), nullable=True),
    sa.Column('public_image_id', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=250), nullable=True),
    sa.Column('role', sa.String(length=250), nullable=True),
    sa.Column('experience', sa.String(length=250), nullable=True),
    sa.Column('hiring', sa.String(length=3), nullable=True),
    sa.Column('looking_for', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('remote', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=250), nullable=False),
    sa.Column('country', sa.String(length=250), nullable=False),
    sa.Column('price_min', sa.String(length=100), nullable=False),
    sa.Column('price_max', sa.String(length=100), nullable=False),
    sa.Column('pictures', sa.String(length=250), nullable=False),
    sa.Column('public_image_id', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=250), nullable=False),
    sa.Column('user_handle', sa.String(length=50), nullable=False),
    sa.Column('profession', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('remote', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=250), nullable=False),
    sa.Column('country', sa.String(length=250), nullable=False),
    sa.Column('price_min', sa.String(length=100), nullable=False),
    sa.Column('price_max', sa.String(length=100), nullable=False),
    sa.Column('pictures', sa.String(length=250), nullable=False),
    sa.Column('public_image_id', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=250), nullable=False),
    sa.Column('user_handle', sa.String(length=50), nullable=False),
    sa.Column('profession', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('requests')
    op.drop_table('profile')
    op.drop_table('users')
    # ### end Alembic commands ###
