"""empty message

Revision ID: 340ac8a30a19
Revises: 0bc09c144748
Create Date: 2024-03-20 19:56:31.633244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340ac8a30a19'
down_revision = '0bc09c144748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profession', sa.String(length=250), nullable=False))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profession', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('profession')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('profession')

    # ### end Alembic commands ###
