"""empty message

Revision ID: 5e1d0f89f192
Revises: 6c66d36c640e
Create Date: 2024-03-12 15:32:06.859860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e1d0f89f192'
down_revision = '6c66d36c640e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remote', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=250), nullable=False))
        batch_op.drop_column('is_remote')
        batch_op.drop_column('province')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remote', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=250), nullable=False))
        batch_op.drop_column('is_remote')
        batch_op.drop_column('province')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', mysql.VARCHAR(length=250), nullable=False))
        batch_op.add_column(sa.Column('is_remote', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('state')
        batch_op.drop_column('remote')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', mysql.VARCHAR(length=250), nullable=False))
        batch_op.add_column(sa.Column('is_remote', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('state')
        batch_op.drop_column('remote')

    # ### end Alembic commands ###
