"""empty message

Revision ID: 64ae7c0c30ee
Revises: 0f8109b7acdc
Create Date: 2024-03-24 17:06:18.099943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ae7c0c30ee'
down_revision = '0f8109b7acdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=250), nullable=False))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
