"""empty message

Revision ID: 6c66d36c640e
Revises: 9234560e1e41
Create Date: 2024-03-08 12:26:16.391621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c66d36c640e'
down_revision = '9234560e1e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('available',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('available',
               existing_type=sa.String(length=250),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)

    # ### end Alembic commands ###
