"""empty message

Revision ID: 9234560e1e41
Revises: 2ea6dbd1b70e
Create Date: 2024-03-08 11:47:41.409541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9234560e1e41'
down_revision = '2ea6dbd1b70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.Boolean(), nullable=False))
        batch_op.drop_column('aviable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aviable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('available')

    # ### end Alembic commands ###
