"""empty message

Revision ID: ab8f96ddfb5d
Revises: 5e1d0f89f192
Create Date: 2024-03-12 15:36:36.535514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab8f96ddfb5d'
down_revision = '5e1d0f89f192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_min', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('price_max', sa.String(length=100), nullable=False))
        batch_op.drop_column('price_range')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_min', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('price_max', sa.String(length=100), nullable=False))
        batch_op.drop_column('price_range')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_range', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('price_max')
        batch_op.drop_column('price_min')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_range', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('price_max')
        batch_op.drop_column('price_min')

    # ### end Alembic commands ###
