"""location

Revision ID: cb1aaf714e02
Revises: abf480ac0096
Create Date: 2024-02-26 11:55:33.244912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb1aaf714e02'
down_revision = 'abf480ac0096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=False))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', mysql.VARCHAR(length=250), nullable=False))
        batch_op.drop_column('province')
        batch_op.drop_column('city')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
